nmpc_engine_node:
  ros__parameters:
    wheelbase: 0.33
    steer_limit: 0.41
    steer_rate_limit: 2.0
    accel_limit: 4.0
    decel_limit: -6.0
    speed_limit: 6.0
    lookahead_distance: 1.5
    use_vref: true
